# Generated by Django 4.2.1 on 2023-05-27 11:53

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uloga',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('username', models.CharField(db_column='KorIme', max_length=20, primary_key=True, serialize=False, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('password', models.CharField(db_column='Sifra', max_length=128)),
                ('email', models.CharField(db_column='Email', max_length=40)),
                ('slika', models.ImageField(db_column='Slika', null=True, upload_to='ulogaImgs/')),
                ('brpratilaca', models.IntegerField(db_column='BrPratilaca', default=0)),
                ('prosecnaocena', models.DecimalField(db_column='ProsecnaOcena', decimal_places=2, default=0, max_digits=5)),
                ('tip', models.CharField(db_column='Tip', default='K', max_length=1)),
                ('banovan', models.BooleanField(db_column='Banovan', default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'uloga',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Knjiga',
            fields=[
                ('isbn', models.CharField(db_column='ISBN', max_length=20, primary_key=True, serialize=False)),
                ('naziv', models.CharField(db_column='Naziv', max_length=40)),
                ('slika', models.ImageField(db_column='Slika', null=True, upload_to='knjigaImgs/')),
                ('opis', models.CharField(blank=True, db_column='Opis', max_length=100, null=True)),
                ('prosecnaocena', models.DecimalField(db_column='ProsecnaOcena', decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'knjiga',
            },
        ),
        migrations.CreateModel(
            name='Licitacija',
            fields=[
                ('idlicitacija', models.IntegerField(db_column='IDLicitacija', primary_key=True, serialize=False)),
                ('nazivdela', models.CharField(db_column='NazivDela', max_length=40)),
                ('pdf', models.FileField(db_column='PDF', null=True, upload_to='pdfs/')),
                ('datumpocetka', models.DateTimeField(db_column='DatumPocetka')),
                ('datumkraja', models.DateTimeField(db_column='DatumKraja')),
                ('pocetnacena', models.IntegerField(db_column='PocetnaCena')),
                ('trenutniiznos', models.IntegerField(db_column='TrenutniIznos')),
            ],
            options={
                'db_table': 'licitacija',
            },
        ),
        migrations.CreateModel(
            name='NajpopularnijiMesec',
            fields=[
                ('idocenjenog', models.CharField(db_column='IDOcenjenog', max_length=20, primary_key=True, serialize=False)),
                ('prosecnaocena', models.DecimalField(db_column='ProsecnaOcena', decimal_places=2, max_digits=5)),
                ('tip', models.CharField(db_column='Tip', max_length=1)),
            ],
            options={
                'db_table': 'najpopularnijimesec',
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('uloga_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('imeprezime', models.CharField(db_column='ImePrezime', max_length=40)),
                ('datumrodjenja', models.DateField(db_column='DatumRodjenja')),
                ('biografija', models.CharField(db_column='Biografija', max_length=1000)),
            ],
            options={
                'db_table': 'autor',
            },
            bases=('citajneskitaj.uloga',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='IzdavackaKuca',
            fields=[
                ('uloga_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('naziv', models.CharField(db_column='Naziv', max_length=40)),
                ('istorija', models.CharField(blank=True, db_column='Istorija', max_length=1000, null=True)),
                ('adresa', models.CharField(db_column='Adresa', max_length=60)),
            ],
            options={
                'db_table': 'izdavackakuca',
            },
            bases=('citajneskitaj.uloga',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('uloga_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('imeprezime', models.CharField(db_column='ImePrezime', max_length=40)),
                ('datumrodjenja', models.DateField(db_column='DatumRodjenja')),
            ],
            options={
                'db_table': 'korisnik',
            },
            bases=('citajneskitaj.uloga',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Recenzija',
            fields=[
                ('idrec', models.IntegerField(db_column='IDRec', primary_key=True, serialize=False)),
                ('ocena', models.IntegerField(db_column='Ocena')),
                ('datumobjave', models.DateTimeField(db_column='DatumObjave')),
                ('tekst', models.CharField(db_column='Tekst', max_length=1000)),
                ('iddavalac', models.ForeignKey(db_column='IDDavalac', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_to_davalac_uloga', to=settings.AUTH_USER_MODEL)),
                ('idprimalacknjiga', models.ForeignKey(blank=True, db_column='IDPrimalacKnjiga', max_length=20, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='citajneskitaj.knjiga')),
                ('idprimalaculoga', models.ForeignKey(blank=True, db_column='IDPrimalacUloga', max_length=20, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_to_primalac_uloga', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recenzija',
            },
        ),
        migrations.CreateModel(
            name='Objava',
            fields=[
                ('idobjava', models.IntegerField(db_column='IDObjava', primary_key=True, serialize=False)),
                ('sadrzaj', models.CharField(db_column='Sadrzaj', max_length=1000)),
                ('datumobjave', models.DateTimeField(db_column='DatumObjave')),
                ('slika', models.ImageField(db_column='Slika', null=True, upload_to='objavaImgs/')),
                ('korime', models.ForeignKey(db_column='KorIme', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'objava',
            },
        ),
        migrations.CreateModel(
            name='Prati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpracen', models.ForeignKey(db_column='IDPracen', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_to_pracen', to=settings.AUTH_USER_MODEL)),
                ('idpratilac', models.ForeignKey(db_column='IDPratilac', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_to_pratilac', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prati',
                'unique_together': {('idpratilac', 'idpracen')},
            },
        ),
        migrations.CreateModel(
            name='Ponuda',
            fields=[
                ('idponuda', models.IntegerField(db_column='IDPonuda', primary_key=True, serialize=False)),
                ('iznos', models.IntegerField(db_column='Iznos')),
                ('idlicitacija', models.ForeignKey(db_column='IDLicitacija', on_delete=django.db.models.deletion.DO_NOTHING, to='citajneskitaj.licitacija')),
                ('idizdkuca', models.ForeignKey(db_column='IDIzdKuca', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='citajneskitaj.izdavackakuca')),
            ],
            options={
                'db_table': 'ponuda',
            },
        ),
        migrations.AddField(
            model_name='licitacija',
            name='idautor',
            field=models.ForeignKey(db_column='IDAutor', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='citajneskitaj.autor'),
        ),
        migrations.AddField(
            model_name='licitacija',
            name='idpobednik',
            field=models.ForeignKey(blank=True, db_column='IDPobednik', max_length=20, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='citajneskitaj.izdavackakuca'),
        ),
        migrations.CreateModel(
            name='Kolekcija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.ForeignKey(db_column='ISBN', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='citajneskitaj.knjiga')),
                ('korime', models.ForeignKey(db_column='KorIme', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kolekcija',
                'unique_together': {('korime', 'isbn')},
            },
        ),
        migrations.AddField(
            model_name='knjiga',
            name='idizdkuca',
            field=models.ForeignKey(db_column='IDIzdKuca', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='citajneskitaj.izdavackakuca'),
        ),
        migrations.CreateModel(
            name='ProdajnaMesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.CharField(db_column='Adresa', max_length=60)),
                ('idizdkuca', models.ForeignKey(db_column='IDIzdKuca', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='citajneskitaj.izdavackakuca')),
            ],
            options={
                'db_table': 'prodajnamesta',
                'unique_together': {('idizdkuca', 'adresa')},
            },
        ),
        migrations.CreateModel(
            name='Povezani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idautor', models.ForeignKey(db_column='IDAutor', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='citajneskitaj.autor')),
                ('idizdkuca', models.ForeignKey(db_column='IDIzdKuca', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='citajneskitaj.izdavackakuca')),
            ],
            options={
                'db_table': 'povezani',
                'unique_together': {('idautor', 'idizdkuca')},
            },
        ),
        migrations.CreateModel(
            name='Napisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.ForeignKey(db_column='ISBN', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='citajneskitaj.knjiga')),
                ('idautor', models.ForeignKey(db_column='IDAutor', max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='citajneskitaj.autor')),
            ],
            options={
                'db_table': 'napisao',
                'unique_together': {('idautor', 'isbn')},
            },
        ),
    ]
