# Generated by Django 4.2.1 on 2023-05-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citajneskitaj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenzija',
            name='ocena',
            field=models.FloatField(db_column='Ocena'),
        ),
    ]
