# Generated by Django 4.2.1 on 2023-05-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citajneskitaj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenzija',
            name='idrec',
            field=models.AutoField(db_column='IDRec', primary_key=True, serialize=False),
        ),
    ]
