# Generated by Django 4.2.1 on 2023-05-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citajneskitaj', '0002_alter_recenzija_idrec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacija',
            name='idlicitacija',
            field=models.AutoField(db_column='IDLicitacija', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='objava',
            name='idobjava',
            field=models.AutoField(db_column='IDObjava', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ponuda',
            name='idponuda',
            field=models.AutoField(db_column='IDPonuda', primary_key=True, serialize=False),
        ),
    ]
