# Generated by Django 4.2.1 on 2023-05-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citajneskitaj', '0002_alter_recenzija_ocena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenzija',
            name='ocena',
            field=models.DecimalField(db_column='Ocena', decimal_places=1, max_digits=5),
        ),
    ]
