# Generated by Django 4.2.1 on 2023-05-29 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citajneskitaj', '0003_alter_licitacija_idlicitacija_alter_objava_idobjava_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenzija',
            name='datumobjave',
            field=models.DateTimeField(db_column='DatumObjave', default=datetime.datetime(2023, 5, 29, 18, 23, 37, 976322)),
        ),
    ]
