# Generated by Django 4.2.1 on 2023-05-30 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citajneskitaj', '0005_alter_recenzija_datumobjave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenzija',
            name='datumobjave',
            field=models.DateTimeField(db_column='DatumObjave', default=datetime.datetime(2023, 5, 30, 14, 11, 50, 686259)),
        ),
        migrations.AlterField(
            model_name='uloga',
            name='slika',
            field=models.ImageField(db_column='Slika', default='ulogaImgs/default.jpg', null=True, upload_to='ulogaImgs/'),
        ),
    ]
