# Generated by Django 4.2.1 on 2023-05-30 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citajneskitaj', '0006_alter_recenzija_datumobjave_alter_uloga_slika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenzija',
            name='datumobjave',
            field=models.DateTimeField(db_column='DatumObjave', default=datetime.datetime(2023, 5, 30, 23, 10, 30, 584630)),
        ),
    ]
