# Generated by Django 4.2.2 on 2023-06-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citajneskitaj', '0009_alter_recenzija_datumobjave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenzija',
            name='datumobjave',
            field=models.DateTimeField(auto_now_add=True, db_column='DatumObjave'),
        ),
    ]
